version: '3'

services:

  redis:
    image: 'bitnami/redis:latest'
    sysctls:
      - net.core.somaxconn=65535
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /home/vagrant/var/Redis:/bitnami/redis/data
    ports:
      - "6379:6379"
    network_mode: "host"
    command: bash -c "/run.sh --maxmemory 8000mb"
    deploy:
      resources:
        reservations:
          cpus: '3'

  index:
    build: ./server/
    command: python index.py 8001
    volumes:
      - ./server:/code
    ports:
      - "8001:8001"
    depends_on:
      - redis

    network_mode: "host"

  web:
    build: ./client/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./client:/code
    ports:
      - "8000:8000"
    depends_on:
      - index
    network_mode: "host"