version: '3'

networks:
  app-tier:
    driver: bridge

services:

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .:/bitnami/redis/data
    ports:
      - "6380:6379"
    networks:
      - app-tier

  index:
    build: ./server/
    command: python index.py 8001
    volumes:
      - ./server:/code
    ports:
      - "8001:8001"
    # depends_on:
    #   - memcached
    networks:
      - app-tier
  web:
    build: ./client/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./client:/code
    ports:
      - "8000:8000"
    depends_on:
      - index
    networks:
      - app-tier